const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    //user
    // ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    //login
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',


    //logout
    PROCESS_LOGOUT: "PROCESS_LOGOUT",

    //Edit trong profile
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',
    UPDATE_USER_INFO: 'UPDATE_USER_INFO',

    //photo user
    UPDATE_USER_PHOTO_SUCCESS: 'UPDATE_USER_PHOTO_SUCCESS',
    UPDATE_USER_PHOTO_FAILED: 'UPDATE_USER_PHOTO_FAILED',

    //ADMIN GET ALL User
    GET_All_USER_SUCCESS: 'GET_All_USER_SUCCESS',
    GET_All_USER_FAILED: 'GET_All_USER_FAILED',

    //ADMIN  edit User
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',

    //xóa user
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    //tạo user
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    // __________________


    //ADMIN
    // ALL Product
    GET_All_PRODUCT_SUCCESS: 'GET_All_PRODUCT_SUCCESS',
    GET_All_PRODUCT_FAILED: 'GET_All_PRODUCT_FAILED',

    //_____CATEGORY
    GET_All_CATEGORY_SUCCESS: 'GET_All_CATEGORY_SUCCESS',
    GET_All_CATEGORY_FAILED: 'GET_All_CATEGORY_FAILED',

    //Edit 
    EDIT_CATEGORY_SUCCESS: 'EDIT_CATEGORY_SUCCESS',
    EDIT_CATEGORY_FAILED: 'EDIT_CATEGORY_FAILED',

    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILED: 'DELETE_CATEGORY_FAILED',

    //tạo 
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILED: 'CREATE_CATEGORY_FAILED',

    //
    GET_All_PRODUCT_CATEGORY_SUCCESS: 'GET_All_PRODUCT_CATEGORY_SUCCESS',
    GET_All_PRODUCT_CATEGORY_FAILED: 'GET_All_PRODUCT_CATEGORY_FAILED',

    //___BRAND
    GET_All_BRAND_SUCCESS: 'GET_All_BRAND_SUCCESS',
    GET_All_BRAND_FAILED: 'GET_All_BRAND_FAILED',

    //Edit 
    EDIT_BRAND_SUCCESS: 'EDIT_BRAND_SUCCESS',
    EDIT_BRAND_FAILED: 'EDIT_BRAND_FAILED',

    DELETE_BRAND_SUCCESS: 'DELETE_BRAND_SUCCESS',
    DELETE_BRAND_FAILED: 'DELETE_BRAND_FAILED',

    //tạo 
    CREATE_BRAND_SUCCESS: 'CREATE_BRAND_SUCCESS',
    CREATE_BRAND_FAILED: 'CREATE_BRAND_FAILED',

    //
    GET_All_PRODUCT_BRAND_SUCCESS: 'GET_All_PRODUCT_BRAND_SUCCESS',
    GET_All_PRODUCT_BRAND_FAILED: 'GET_All_PRODUCT_BRAND_FAILED',

    //___Type
    GET_All_TYPE_SUCCESS: 'GET_All_TYPE_SUCCESS',
    GET_All_TYPE_FAILED: 'GET_All_TYPE_FAILED',

    //Edit 
    EDIT_TYPE_SUCCESS: 'EDIT_TYPE_SUCCESS',
    EDIT_TYPE_FAILED: 'EDIT_TYPE_FAILED',

    DELETE_TYPE_SUCCESS: 'DELETE_TYPE_SUCCESS',
    DELETE_TYPE_FAILED: 'DELETE_TYPE_FAILED',

    //tạo 
    CREATE_TYPE_SUCCESS: 'CREATE_TYPE_SUCCESS',
    CREATE_TYPE_FAILED: 'CREATE_TYPE_FAILED',

    //GET ALL
    GET_All_PRODUCT_TYPE_SUCCESS: 'GET_All_PRODUCT_TYPE_SUCCESS',
    GET_All_PRODUCT_TYPE_FAILED: 'GET_All_PRODUCT_TYPE_FAILED',

    //__Product

    GET_All_PRODUCT_SUCCESS: 'GET_All_PRODUCT_SUCCESS',
    GET_All_PRODUCT_FAILED: 'GET_All_PRODUCT_FAILED',

    //Edit 
    EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
    EDIT_PRODUCT_FAILED: 'EDIT_PRODUCT_FAILED',

    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',

    //tạo 
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILED: 'CREATE_PRODUCT_FAILED',

    //GET ALL
    GET_All_PRODUCT_TYPE_SUCCESS: 'GET_All_PRODUCT_TYPE_SUCCESS',
    GET_All_PRODUCT_TYPE_FAILED: 'GET_All_PRODUCT_TYPE_FAILED',

    //detailProduct
    GET_DETAIL_PRODUCT_SUCCESS: 'GET_DETAIL_PRODUCT_SUCCESS',
    GET_DETAIL_PRODUCT_FAILED: 'GET_DETAIL_PRODUCT_FAILED',

    //search product
    GET_SEARCH_PRODUCT_SUCCESS: 'GET_SEARCH_PRODUCT_SUCCESS',
    GET_SEARCH_PRODUCT_FAILED: 'GET_SEARCH_PRODUCT_FAILED',
    //makeup 
    GET_MAKEUP_PRODUCT_SUCCESS: 'GET_MAKEUP_PRODUCT_SUCCESS',
    GET_MAKEUP_PRODUCT_FAILED: 'GET_MAKEUP_PRODUCT_FAILED',

    GET_SKIN_PRODUCT_SUCCESS: 'GET_SKIN_PRODUCT_SUCCESS',
    GET_SKIN_PRODUCT_FAILED: 'GET_SKIN_PRODUCT_FAILED',

    GET_HAIR_PRODUCT_SUCCESS: 'GET_HAIR_PRODUCT_SUCCESS',
    GET_HAIR_PRODUCT_FAILED: 'GET_HAIR_PRODUCT_FAILED',

    //price
    GET_PRICE_PRODUCT_SUCCESS: 'GET_PRICE_PRODUCT_SUCCESS',
    GET_PRICE_PRODUCT_FAILED: 'GET_PRICE_PRODUCT_FAILED',

    //bán chạy
    GET_TOP_PRODUCT_SUCCESS: 'GET_TOP_PRODUCT_SUCCESS',
    GET_TOP_PRODUCT_FAILED: 'GET_TOP_PRODUCT_FAILED',

    //ORDER
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED',

    //
    LIST_ORDER_SUCCESS: "LIST_ORDER_SUCCESS",
    LIST_ORDER_FAILED: "LIST_ORDER_FAILED",

    //add product vào cart
    ADD_PRODUCT_ORDER_SUCCESS: "ADD_PRODUCT_ORDER_SUCCESS",
    ADD_PRODUCT_ORDER_FAILED: "ADD_PRODUCT_ORDER_FAILED",

    DELETE_PRODUCT_ORDER_SUCCESS: "DELETE_PRODUCT_ORDER_SUCCESS",
    DELETE_PRODUCT_ORDER_FAILED: "DELETE_PRODUCT_ORDER_FAILED",

    //change
    CHANGE_AMOUNT_ORDER_SUCCESS: "CHANGE_AMOUNT_ORDER_SUCCESS",
    CHANGE_AMOUNT_ORDER_FAILED: "CHANGE_AMOUNT_ORDER_FAILED",

    //checkout
    CHECK_OUT_ORDER_SUCCESS: "CHECK_OUT_ORDER_SUCCESS",
    CHECK_OUT_ORDER_FAILED: "CHECK_OUT_ORDER_FAILED",

    //checkout
    VALUE_ORDER_SUCCESS: "VALUE_ORDER_SUCCESS",
    VALUE_ORDER_FAILED: "VALUE_ORDER_FAILED",

    //freeship
    FREE_SHIP_SUCCESS: "FREE_SHIP_SUCCESS",
    FREE_SHIP_FAILED: "FREE_SHIP_FAILED",

    //
    TOTAL_SHIP_SUCCESS: "TOTAL_SHIP_SUCCESS",
    TOTAL_SHIP_FAILED: "TOTAL_SHIP_FAILED",

    //get all order
    GET_ALL_ORDERS_SUCCESS: "GET_ALL_ORDERS_SUCCESS",
    GET_ALL_ORDERS_FAILED: "GET_ALL_ORDERS_FAILED",

    //change status
    STATUS_ORDERS_SUCCESS: "STATUS_ORDERS_SUCCESS",
    STATUS_ORDERS_FAILED: "STATUS_ORDERS_FAILED",

    //lịc order
    GET_STATUS_ORDERS_SUCCESS: "GET_STATUS_ORDERS_SUCCESS",
    GET_STATUS_ORDERS_FAILED: "GET_STATUS_ORDERS_FAILED",

    //
    REVIEW_PRODUCT_SUCCESS: 'REVIEW_PRODUCT_SUCCESS',
    REVIEW_PRODUCT_FAILED: 'REVIEW_PRODUCT_FAILED',
});

export default actionTypes;