const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    //user
    // ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    //login
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',


    //logout
    PROCESS_LOGOUT: "PROCESS_LOGOUT",

    //Edit trong profile
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',
    UPDATE_USER_INFO: 'UPDATE_USER_INFO',

    //photo user
    UPDATE_USER_PHOTO_SUCCESS: 'UPDATE_USER_PHOTO_SUCCESS',
    UPDATE_USER_PHOTO_FAILED: 'UPDATE_USER_PHOTO_FAILED',

    //ADMIN GET ALL User
    GET_All_USER_SUCCESS: 'GET_All_USER_SUCCESS',
    GET_All_USER_FAILED: 'GET_All_USER_FAILED',

    //ADMIN  edit User
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',

    //xóa user
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    //xóa user
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    // __________________



    //ADMIN GET ALL Product
    GET_All_PRODUCT_SUCCESS: 'GET_All_PRODUCT_SUCCESS',
    GET_All_PRODUCT_FAILED: 'GET_All_PRODUCT_FAILED',



    //59 save user TỨC TẠO MỚI USER
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    //60 lấy user đã tạo ra màn hình
    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAILED: 'FETCH_ALL_USER_FAILED',




    //
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',
});

export default actionTypes;